### ISSUE TITLE
Can I use the setter function to append to an array in the store and then refetch the list of todos?

### ISSUE THREAD

**Issue by martisj** [sveltetools/svelte-asyncable#11]
Not sure how to ask this questions properly:
I have a todo list: the `getter` from asyncable works like magic 🪄 However trying to pass the second argument `setter` is proving difficult.

```ts
export const todos = asyncable(
  async () => {
    const res = await fetch('todos')
    return res.json() || []
  },
  ($prev: Todo[], $new: Todo[]) => {
    return $new
  }
)
```

And then with the value from an input field I want to add the new todo:

```ts
  async function postTodo(title: string) {
    vaneStore.set([...$vaneStore, { title }])
  }
```
^ this doesn't work. I can't wrap my head around how to update the store with setter stuff?
Any help would be mighty appreciated 🙏

**Comment by PaulMaly** [comment]
Hi @martisj. I hope I understand your question and try to explain.

First of all, you don't need to have `setter` callback to update the store. You just need to update it using store's built-in methods, e.g. set/update. Usually, it looks like:

```javascript
todos.update(($todos) => {
    $todos.push({ title });
    return $todos;
});
```

The second thing is that `setter` callback doesn't return any value. It's needed to provide some side-effect when yout store has changed. For example, posting new values to the server:

```javascript
export const todos = asyncable(
  async () => {
    const res = await fetch('todos');
    return res.json() || []
  },
  async ($todos: Todo[], $prevTodos: Todo[]) => {
     const newTodos = $todos.filter(...);
     ...
     for (let i = 0; i < newTodos.length; i++) {
         await saveTodo(newTodos[i]);
     }
  }
)
```

So, this side-effect gives you the ability to save any added todos to the server right just when you add it to the store. Btw, seems you swap `setter` arguments in your examples.

I'm not sure am I answered your question, so feel free to clarify any details you need.

**Comment by martisj** [comment]
Aha! @PaulMaly thank you for clarifying, this does indeed answer my question (months later ☺️)

**Comment by PaulMaly** [comment]
@martisj Sorry about that, I know  I'm a bad maintainer )))
