### ISSUE TITLE
This is nice but expected caching

### ISSUE THREAD

**Issue by CraigChamberlain** [sveltetools/svelte-asyncable#2]
I'm not sure if I'm missing something here, should this cache results.  I've kind of got this working now but not totally sure I'm a lot further ahead.  is it essential to setup a $user store in addition to the asyncable?

**Comment by PaulMaly** [comment]
Hi! What do you mean by caching the result? Unfortunately, README of this package is really bad, sorry about it. I plan to improve descriptions and use-cases in the near future, but for now, I can help you directly.

If I understand your question you asking about `getter`. So, this effect will be performed in the following cases:

1. Each time when the first subscriber occurred. 
2. Each time when related stores have changed.

So, if you want to perform `getter` effect only once and after that use `asyncable` to store and work with this value, you should hold at least one subscription to `asyncable` store. Right after the counter of subscribers will goes to 0, `getter` effect will be executed again on the next subscription and the previous value will be lost.

But you can override this behavior in two ways:

1) cache the first value manually and return next time:

```javascript

let cache;
const store = asyncable(() => {
       return cache || (cache = getData());
}, );
```

2) return `undefined` from `getter` if you need to keep the previous value:

```javascript

let hasValue = false;
const store = asyncable(() => {
       if (hasValue) return;
       hasValue = true;
       return getData();
}, );
```

I hope, it would help you. Feel free to ask if something still not clear!

**Comment by CraigChamberlain** [comment]
Thanks for getting back so quick.  Basically I was just confused as to expected behaviour.  I was only able to access with the getter so that was half of my problem.  Does an asyncable have a subscribe method?  I was also confused how to use it in the $user in the consuming component.  

I think the subscribers being 0 is also an important point.  If I navigate away from a page and back again the data is going to be lost as standard.  For now, I'm just back to native svelte stores as I think I need to understand them first too, to see what asyncable is adding. 

```
//store.js
export async function getAllWorks() {
    return await fetchDato(body).then( r=> r.allWorks );
};

export const worksStore = writable([]);

//Component.svelte
  import { getAllPins, pinsStore } from '../../scripts/pins'
  async function pins() {
      if($pinsStore.length == 0){
          await getAllPins().then(r => $pinsStore = r)
      }
  }

    onMount(async() =>{
      await pins()   
    })

...
{#each $pinsStore as pin }
```

**Comment by CraigChamberlain** [comment]
Now I'm thinking about it, is your examples in a svelte file not a js file?  Would account for my problems using $user.

**Comment by PaulMaly** [comment]
> Does an asyncable have a subscribe method?  I was also confused how to use it in the $user in the consuming component.

Sure, `asyncable` is a svelte store, so it respects [a contract described in docs](https://svelte.dev/docs#4_Prefix_stores_with_$_to_access_their_values). In other words, in component files (`.svelte`) you can get access to its value using `$` prefix. But you should remember that `asyncable` stores the value as Promise and you should resolve it first.

> I think the subscribers being 0 is also an important point. If I navigate away from a page and back again the data is going to be lost as standard. 

Yea, it's design intent, because if you leave from the page and go back again, implying that the data may have changed in the data source and should be retrieved again. However, you can create a blank subscription for critical data somewhere in root component which won't be unmounted on navigation.


> Now I'm thinking about it, is your examples in a svelte file not a js file? 
I'm not sure, I've got your question.

**Comment by PaulMaly** [comment]
> Does an asyncable have a subscribe method? I was also confused how to use it in the $user in the consuming component.

Sure, `asyncable` is a svelte store, so it respects [a contract described in docs](https://svelte.dev/docs#4_Prefix_stores_with_$_to_access_their_values). In other words, in component files (`.svelte`) you can get access to its value using `$` prefix. But you should remember that `asyncable` stores the value as Promise and you should resolve it first.

> I think the subscribers being 0 is also an important point. If I navigate away from a page and back again the data is going to be lost as standard.

Yea, it's design intent, because if you leave from the page and go back again, implying that the data may have changed in the data source and should be retrieved again. However, you can create a blank subscription for critical data somewhere in root component which won't be unmounted on navigation.

Also, your example can be re-written wtih `asyncable` like this:

```
//store.js
import { asyncable } from 'svelte-asyncable';

export const pinsStore = asyncable(async () => {
    const $pinstStore = await pinsStore.get();
    if ($pinstStore.length > 0) return;
    return getAllPins();
});

//Component.svelte

import { pinsStore } from '../../scripts/pins';
...
{#await $pinsStore}
  Loading pins...
{:then pins}
  {#each pins as pin}
  ...
  {/each}
{:catch err}
   Pins loading error
{/await}
```

In places where you don't need to have pending/error states of your async store, you can always use it `syncable` version:

```
//store.js
import { asyncable, syncable } from 'svelte-asyncable';

export const pinsStore = asyncable(async () => {
    const $pinstStore = await pinsStore.get();
    if ($pinstStore.length > 0) return;
    return getAllPins();
});

export const pinsStoreSync = syncable(pinsStore, []);

//Component.svelte

import { pinsStoreSync } from '../../scripts/pins';
...
{#each $pinsStoreSync as pin}
  ...
{/each}
```



> Now I'm thinking about it, is your examples in a svelte file not a js file?

I'm not sure, I caught your question. The only difference in use stores in `.svelte` and `.js` files is that in `.svelte` files we've syntax sugar with auto-subscriptions. So:

```javascript
$store (.svelte) === store.subsctibe() (.js)
$store = value (.svelte) === store.set(value) (.js)
```

All this rules applicable to `asyncable` store as well. The only feature that is not supported by `asyncable` is two-way bindings.

**Comment by CraigChamberlain** [comment]
Amazing.  So kind to get back with all that detail.  I though .subscribe() had to be more complex with local assignments and a destructor call back was a bit outfaced.

I should be able to get my code quite a bit more concise with this help.

Are the first two lines of this this even necessary if I use the subscribe functionality instead of the getter?   I thought perhaps it did keep a cached version while a subscription was active? 

> 
> ```
> export const pinsStore = asyncable(async () => {
>     const $pinstStore = await pinsStore.get(); 
>     if ($pinstStore.length > 0) return;
>     return getAllPins();
> });
> 
> ```

The syncable option is also really nice for components that handle dynamic loading.  I've been working with a few galleries that have to be initialised with complete data hence the need for both.

**Comment by PaulMaly** [comment]
> Are the first two lines of this this even necessary if I use the subscribe functionality instead of the getter? I thought perhaps it did keep a cached version while a subscription was active?

The only purpose of the first two lines is only to keep already fetched value even if a subscription was dropped. Actually, it's not a common usage of `asyncable` store, but it possible if needed. I assume that in real-life code conditions would be more specific. So, if it's ok for you if data will be re-fetched each time when the first subscriber occurred, this example could be simplified more:

```svelte
export const pinsStore = asyncable(getAllPins);
```

This `getter` will be performed ONLY on the first subscriber (lazy approach), value will be cached while at least one subscriber exists and will be re-written by the next `getter` call. 

> The syncable option is also really nice for components that handle dynamic loading. I've been working with a few galleries that have to be initialised with complete data hence the need for both.

The main reason to use `asyncable` when you need to get control on async/dynamic data fetching and have full info about its status (pending/fulfilled/rejected) in any place you use it. For example, getting async value once just inside the function:

```javascript
async function doSomethingAfterDataLoad() {
      const data = await store.get();
      //  do something with this data
}
```
`syncalbe` store is just a mirror of `asyncable` store and can be only in 2 states: initial value and fulfilled state of a Promise.

**Comment by CraigChamberlain** [comment]
This information is all super useful, would it be any help if I tried to use it to add to the README?  It's your product so obviously not my place start interfering.  I understand Documentation is actually one of the most in demand contribution areas though so thought I might as well offer.

**Comment by PaulMaly** [comment]
Sure, PRs are always welcome!

**Comment by CraigChamberlain** [comment]
```javascript
export const pinsStore = asyncable(async () => {
    const $pinstStore = await pinsStore.get(); 
    if ($pinstStore.length > 0) return;
    return getAllPins();
});
```
btw, this seems to cause the process to fail. It doesn't produce an error.  I guess it never completes.  I even tried just loging pinsStore.get() and even this caused the block.   I guess .get() either starts an infinite recursive loop or some other failure that aborts silently?

**Comment by PaulMaly** [comment]
@CraigChamberlain Ugh, shame on me, but I forgot about your request. Really sorry about that, I'm a really bad maintainer.

I know, most likely it's not actual anymore, but for historical purposes. We just need to implement some kind of guard for the first resolution of a promise. The simplest way may look like this:


```javascript

let resolved = false;

export const pinsStore = asyncable(async () => {
    if (resolved) {
        const $pinstStore = await pinsStore.get(); 
        if ($pinstStore.length > 0) return;
    }
    resolved = true;
    return getAllPins();
});
```
