### ISSUE TITLE
Callback when there are no subscribers

### ISSUE THREAD

**Issue by nikicat** [sveltetools/svelte-asyncable#25]
Hello, I want to make an async store that automatically updates on notification froma server side (using websockets), but this case I need to call `await ws.close()` when there are no more subscribers to the store, how can I achieve that?

**Comment by PaulMaly** [comment]
Hi, not sure, but possible it would be better to use [svelte-websocket-store](https://www.npmjs.com/package/svelte-websocket-store) for this purpose. It will call `ws.close()` automatically for you.

**Comment by PaulMaly** [comment]
I'm not sure I fully understand you implementation, but I try to imagine how I would solve this problem (without fork and changing api of asyncable store):


```javascript

const notificationUpdates = readable(null, set => {
    const socket = new WebSocket(url, socketOptions);
    ...
    return () => socket.close();
});

const notifications = asyncable(fetchNotifications, null, [ notificationUpdates ]);
```

It's not full and ready-to-use implementation, but I think the idea is clear - `notificationUpdates` is a read-only store to control the state of websocket connection. It will initialized when asyncable store will get first subscriber and socket will be closed when there're no more subscribers of the asyncable store.

**Comment by PaulMaly** [comment]
@nikicat Solution was found basically, I think we can close this issue. Feel free to re-open it when you needed.

**Comment by nikicat** [comment]
Hmm, may be this will work if I set inner store to WebSocket object. Thank you for the idea!
