### ISSUE TITLE
IndexedDB?

### ISSUE THREAD

**Issue by frederikhors** [sveltetools/svelte-asyncable#29]
Amazing project, congratulations!

Is there a way to persist to IndexedDB?

**Comment by PaulMaly** [comment]
Hi, thanks! 

> Is there a way to persist to IndexedDB?

No doubt, there is. You can perform any side-effect you need for `get` or `set` operation of the store. Basic example can be:


```javascript
export const persistedData = asyncable(async () => {
     let data = await readFromDB();
     if ( ! data) {
         data = await fetchFromServer();
         storeInDB(data);
     }
     return data;
}, (data) => {
    storeInDB(data);
});


```

**Comment by PaulMaly** [comment]
Complex example of what? Persistence to IndexedDB? it's not related to this particular project.
